export const utilitiesItems = [
    { text: 'Введение', link: '/utilities/' },
    { text: 'Палитра', link: '/utilities/colors' },
    { text: 'Position', link: '/utilities/position' },
    { text: 'Spacing', link: '/utilities/spacing' },
    { text: 'Flex', link: '/utilities/flex' },
    { text: 'Typography', link: '/utilities/typography' },
    { text: 'Display', link: '/utilities/display' },
    { text: 'Overflow', link: '/utilities/overflow' },
    { text: 'Sizing', link: '/utilities/sizing' },
    { text: 'Opacity', link: '/utilities/opacity' },
    { text: 'Text', link: '/utilities/text' },
    { text: 'Radius', link: '/utilities/radius' },
    { text: 'Elevation', link: '/utilities/elevation' },
]
